---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest(ingest)
	validate(validate)
	decide(decide)
	critique(critique)
	pay(pay)
	record(record)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest;
	critique -.-> decide;
	critique -.-> pay;
	critique -.-> record;
	decide --> critique;
	ingest -.-> record;
	ingest -.-> validate;
	pay --> record;
	validate -.-> decide;
	validate -.-> record;
	record --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
